remote_theme: coursweb/jk-theme
title: Projet interface
description: Cours Projet Interface.
lang: fr-FR
robots: noindex, nofollow
markdown: GFM
# menu 
chapters:
 - title: ğŸ’» Cours Dev 2
   url: https://eracom-id301.github.io/cours-dev2-css/
 - title: ğŸ’ Cours Projet Interface
   url: https://eracom-id301.github.io/cours-projet-interface/
# - title: â„¹ï¸ Infos IMD
#   url: https://eracom.ch/informations-eleves-id/
# - title: Plan de formation
#   url: https://code.eracom-pedagogique.ch/formation-imd-2020/
# - title: ğŸ”  Fontes IMD
#   url: https://code.eracom-pedagogique.ch/fontes-imd/   
 - title: ğŸ€ Teams
   url: https://teams.microsoft.com/l/team/19%3aCbnAyUJ9N9j9yjE_J-RA7aJtVx_O88h5oDMuwfmDZH01%40thread.tacv2/conversations?groupId=224acda1-df49-46e7-a63e-d878443c0616&tenantId=906ab908-04f9-4a80-ba9c-875a36e77bc1
 - title: ğŸ§  Podsie
   url: https://student.podsie.org/
# pied de page   
footer_col_1: <ul class="contact-list">
  <li>Eracom, Lausanne</li>
  <li>2017-2021</li></ul>
footer_col_2: <ul class="social-media-list"><li><a href="https://github.com/eracom-id301/cours-projet-interface">Lien Github</a></li></ul>
